run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  errcheck:
    check-type-assertions: true
